name: sogos
channels:
  - conda-forge
dependencies:
  - python
  - datashader
  - geoviews
  - hvplot
  - gsw
  - fsspec
  - numexpr
  - pytest
  - jupyter
  - jupyterlab=2
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - pykrige
  - pip=20
  - h5py
  - cartopy==0.18
  - cmocean
  - xrft
  - glidertools
  - pip:
    - requests
    - ecmwf-api-client
    - geo_tools
    - progressbar
    - geographiclib
    - pyshp
    - wget
    - nc-time-axis
    - jedi==0.17.2
    - gpy
    - jax
